<div>
    <form action="<?php echo Mage::getUrl('*/adminhtml_banner/save', array('group_id' => $this->getRequest()->getParam('group_id'))); ?>" method="post">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div style="display:flex;">
            <div style="width: 90%"><h2><b>Manage Banner Grid</b></h2></div>
            <div style="width: 10%"><button type="submit">Save</button></div>
        </div>
        <div style="margin-bottom: 25px;">
            <table width="100%" border="1">
                <tr>
                    <th>Banner Id</th>
                    <th>Group Key</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th>Position</th>
                    <th>Created At</th>
                </tr>
                <?php foreach ($this->getCollection()->getItems() as $data) : ?>
                <tr>
                    <td><?php echo $data->banner_id ?></td>
                    <td><?php echo $data->getGroupKey() ?></td>
                    <td><img src="<?php echo Mage::getBaseUrl('media') . 'banner/resized/' . $data->image ?>" alt="Invalid Image"></td>
                    <td>
                        <select name="status[<?php echo $data->banner_id ?>]">
                            <?php $selected = ($data->status == 1) ? "selected" : "" ; ?>
                            <option value="1" <?php echo $selected ?>>Active</option>
                            <?php $selected = ($data->status == 2) ? "selected" : "" ; ?>
                            <option value="2" <?php echo $selected ?>>Inctive</option>
                        </select>
                    </td>
                    <td><input name="position[<?php echo $data->banner_id ?>]" type="text" value="<?php echo $data->position ?>" style='width: 50%;' ></td>
                    <td><?php echo $data->created_at ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </form>
</div>
<div>
    <form action="<?php echo Mage::getUrl('*/adminhtml_banner/uploadImage', ['group_id'=>$this->getRequest()->getParam('group_id')]); ?>" method="post" enctype="multipart/form-data">
        <?php echo $this->getBlockHtml('formkey') ?>
        <input type="file" name="images[]" multiple>
        <button type="submit">Upload</button>
    </form>
</div>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      var fileInput = document.getElementById('images');
      var submitButton = document.getElementById('submitButton');
      
      fileInput.addEventListener('change', function() {
        if (fileInput.files.length > 0) {
          submitButton.disabled = false;
        } else {
          submitButton.disabled = true;
        }
      });
    });
</script>